services:
  postgres:
    image: postgres:15
    container_name: admin_db_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_MULTIPLE_DATABASES: metadata_db,app_dev,app_test,app_stage,app_prod
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
    networks:
      - admin_db_network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  admin_db_network:
    driver: bridge